#pragma once

#include "app_interface.hpp"
#include "nstl/prof/prof_include.hpp"
#include "nstl/content/content_include.hpp"
#include "nstl/file_stream/file_stream_include.hpp"
#include "nstl/artifact/artifact_include.hpp"
#include "nstl/text/text_include.hpp"
#include "nstl/draw2d/draw2d_include.hpp"
#include "nstl/ui/ui_include.hpp"
#include "app/shaders/shader_manifest.h"
#include "app/shaders/shader_records.generated.hpp"
#include "app/assets/asset_formats.hpp"
#include "app_game_kernels.hpp"
#include "app_scene_kernels.hpp"
#include "app_state.hpp"
#include "app_renderer.hpp"
#include "app_debug_draw.hpp"
