#pragma once

#define ENG_SHADER_MANIFEST_SOURCE "engine/shaders/shader_manifest.h"
#define ENG_SHADER_OUTPUT_DIR "build/app/shaders"

#define ENG_SHADER_SLANG_DRAW2D_SOURCE "engine/shaders/draw2d.slang"
#define ENG_SHADER_SLANG_WORLD_SOURCE "engine/shaders/world.slang"
#define ENG_SHADER_SLANG_WORLD_CULL_SOURCE "engine/shaders/world_cull.slang"
#define ENG_SHADER_SLANG_ABI_SOURCE "engine/shaders/gfx_shader_abi.slang"
#define ENG_SHADER_SLANG_RECORDS_SOURCE "engine/shaders/shader_records.generated.hpp"

#define ENG_SHADER_DRAW2D_VERTEX_ENTRY "draw2d_vertex"
#define ENG_SHADER_DRAW2D_FRAGMENT_ENTRY "draw2d_fragment"
#define ENG_SHADER_WORLD_VERTEX_ENTRY "world_vertex"
#define ENG_SHADER_WORLD_FRAGMENT_ENTRY "world_fragment"
#define ENG_SHADER_WORLD_RESET_ENTRY "world_reset"
#define ENG_SHADER_WORLD_CULL_ENTRY "world_cull"
#define ENG_SHADER_WORLD_PREFIX_ENTRY "world_prefix"
#define ENG_SHADER_WORLD_SCATTER_ENTRY "world_scatter"
#define ENG_SHADER_WORLD_ARGS_ENTRY "world_args"

#define ENG_SHADER_VK_DRAW2D_VERTEX_OUTPUT ENG_SHADER_OUTPUT_DIR "/draw2d_vertex.spv"
#define ENG_SHADER_VK_DRAW2D_FRAGMENT_OUTPUT ENG_SHADER_OUTPUT_DIR "/draw2d_fragment.spv"
#define ENG_SHADER_VK_WORLD_VERTEX_OUTPUT ENG_SHADER_OUTPUT_DIR "/world_vertex.spv"
#define ENG_SHADER_VK_WORLD_FRAGMENT_OUTPUT ENG_SHADER_OUTPUT_DIR "/world_fragment.spv"
#define ENG_SHADER_VK_WORLD_RESET_OUTPUT ENG_SHADER_OUTPUT_DIR "/world_reset.spv"
#define ENG_SHADER_VK_WORLD_CULL_OUTPUT ENG_SHADER_OUTPUT_DIR "/world_cull.spv"
#define ENG_SHADER_VK_WORLD_PREFIX_OUTPUT ENG_SHADER_OUTPUT_DIR "/world_prefix.spv"
#define ENG_SHADER_VK_WORLD_SCATTER_OUTPUT ENG_SHADER_OUTPUT_DIR "/world_scatter.spv"
#define ENG_SHADER_VK_WORLD_ARGS_OUTPUT ENG_SHADER_OUTPUT_DIR "/world_args.spv"

#define ENG_SHADER_METAL_DRAW2D_VERTEX_OUTPUT ENG_SHADER_OUTPUT_DIR "/draw2d_vertex.metal"
#define ENG_SHADER_METAL_DRAW2D_FRAGMENT_OUTPUT ENG_SHADER_OUTPUT_DIR "/draw2d_fragment.metal"
#define ENG_SHADER_METAL_WORLD_VERTEX_OUTPUT ENG_SHADER_OUTPUT_DIR "/world_vertex.metal"
#define ENG_SHADER_METAL_WORLD_FRAGMENT_OUTPUT ENG_SHADER_OUTPUT_DIR "/world_fragment.metal"
#define ENG_SHADER_METAL_WORLD_RESET_OUTPUT ENG_SHADER_OUTPUT_DIR "/world_reset.metal"
#define ENG_SHADER_METAL_WORLD_CULL_OUTPUT ENG_SHADER_OUTPUT_DIR "/world_cull.metal"
#define ENG_SHADER_METAL_WORLD_PREFIX_OUTPUT ENG_SHADER_OUTPUT_DIR "/world_prefix.metal"
#define ENG_SHADER_METAL_WORLD_SCATTER_OUTPUT ENG_SHADER_OUTPUT_DIR "/world_scatter.metal"
#define ENG_SHADER_METAL_WORLD_ARGS_OUTPUT ENG_SHADER_OUTPUT_DIR "/world_args.metal"

#define ENG_SHADER_SOURCE_LIST(X) \
    X(Draw2dSlang, ENG_SHADER_SLANG_DRAW2D_SOURCE) \
    X(WorldSlang, ENG_SHADER_SLANG_WORLD_SOURCE) \
    X(WorldCullSlang, ENG_SHADER_SLANG_WORLD_CULL_SOURCE) \
    X(GfxShaderAbiSlang, ENG_SHADER_SLANG_ABI_SOURCE) \
    X(ShaderRecordsSlang, ENG_SHADER_SLANG_RECORDS_SOURCE)

#define ENG_SHADER_VULKAN_OUTPUT_LIST(X) \
    X(Draw2dVertex, ENG_SHADER_SLANG_DRAW2D_SOURCE, ENG_SHADER_VK_DRAW2D_VERTEX_OUTPUT, ENG_SHADER_DRAW2D_VERTEX_ENTRY, vertex, graphics) \
    X(Draw2dFragment, ENG_SHADER_SLANG_DRAW2D_SOURCE, ENG_SHADER_VK_DRAW2D_FRAGMENT_OUTPUT, ENG_SHADER_DRAW2D_FRAGMENT_ENTRY, fragment, graphics) \
    X(WorldVertex, ENG_SHADER_SLANG_WORLD_SOURCE, ENG_SHADER_VK_WORLD_VERTEX_OUTPUT, ENG_SHADER_WORLD_VERTEX_ENTRY, vertex, graphics) \
    X(WorldFragment, ENG_SHADER_SLANG_WORLD_SOURCE, ENG_SHADER_VK_WORLD_FRAGMENT_OUTPUT, ENG_SHADER_WORLD_FRAGMENT_ENTRY, fragment, graphics) \
    X(WorldReset, ENG_SHADER_SLANG_WORLD_CULL_SOURCE, ENG_SHADER_VK_WORLD_RESET_OUTPUT, ENG_SHADER_WORLD_RESET_ENTRY, compute, compute) \
    X(WorldCull, ENG_SHADER_SLANG_WORLD_CULL_SOURCE, ENG_SHADER_VK_WORLD_CULL_OUTPUT, ENG_SHADER_WORLD_CULL_ENTRY, compute, compute) \
    X(WorldPrefix, ENG_SHADER_SLANG_WORLD_CULL_SOURCE, ENG_SHADER_VK_WORLD_PREFIX_OUTPUT, ENG_SHADER_WORLD_PREFIX_ENTRY, compute, compute) \
    X(WorldScatter, ENG_SHADER_SLANG_WORLD_CULL_SOURCE, ENG_SHADER_VK_WORLD_SCATTER_OUTPUT, ENG_SHADER_WORLD_SCATTER_ENTRY, compute, compute) \
    X(WorldArgs, ENG_SHADER_SLANG_WORLD_CULL_SOURCE, ENG_SHADER_VK_WORLD_ARGS_OUTPUT, ENG_SHADER_WORLD_ARGS_ENTRY, compute, compute)

#define ENG_SHADER_METAL_OUTPUT_LIST(X) \
    X(Draw2dVertex, ENG_SHADER_SLANG_DRAW2D_SOURCE, ENG_SHADER_METAL_DRAW2D_VERTEX_OUTPUT, ENG_SHADER_DRAW2D_VERTEX_ENTRY, vertex, graphics) \
    X(Draw2dFragment, ENG_SHADER_SLANG_DRAW2D_SOURCE, ENG_SHADER_METAL_DRAW2D_FRAGMENT_OUTPUT, ENG_SHADER_DRAW2D_FRAGMENT_ENTRY, fragment, graphics) \
    X(WorldVertex, ENG_SHADER_SLANG_WORLD_SOURCE, ENG_SHADER_METAL_WORLD_VERTEX_OUTPUT, ENG_SHADER_WORLD_VERTEX_ENTRY, vertex, graphics) \
    X(WorldFragment, ENG_SHADER_SLANG_WORLD_SOURCE, ENG_SHADER_METAL_WORLD_FRAGMENT_OUTPUT, ENG_SHADER_WORLD_FRAGMENT_ENTRY, fragment, graphics) \
    X(WorldReset, ENG_SHADER_SLANG_WORLD_CULL_SOURCE, ENG_SHADER_METAL_WORLD_RESET_OUTPUT, ENG_SHADER_WORLD_RESET_ENTRY, compute, compute) \
    X(WorldCull, ENG_SHADER_SLANG_WORLD_CULL_SOURCE, ENG_SHADER_METAL_WORLD_CULL_OUTPUT, ENG_SHADER_WORLD_CULL_ENTRY, compute, compute) \
    X(WorldPrefix, ENG_SHADER_SLANG_WORLD_CULL_SOURCE, ENG_SHADER_METAL_WORLD_PREFIX_OUTPUT, ENG_SHADER_WORLD_PREFIX_ENTRY, compute, compute) \
    X(WorldScatter, ENG_SHADER_SLANG_WORLD_CULL_SOURCE, ENG_SHADER_METAL_WORLD_SCATTER_OUTPUT, ENG_SHADER_WORLD_SCATTER_ENTRY, compute, compute) \
    X(WorldArgs, ENG_SHADER_SLANG_WORLD_CULL_SOURCE, ENG_SHADER_METAL_WORLD_ARGS_OUTPUT, ENG_SHADER_WORLD_ARGS_ENTRY, compute, compute)

#if defined(PLATFORM_OS_WINDOWS) || defined(SOB_WINDOWS)
#define ENG_SHADER_DRAW2D_VERTEX_RUNTIME_PATH ENG_SHADER_VK_DRAW2D_VERTEX_OUTPUT
#define ENG_SHADER_DRAW2D_FRAGMENT_RUNTIME_PATH ENG_SHADER_VK_DRAW2D_FRAGMENT_OUTPUT
#define ENG_SHADER_WORLD_VERTEX_RUNTIME_PATH ENG_SHADER_VK_WORLD_VERTEX_OUTPUT
#define ENG_SHADER_WORLD_FRAGMENT_RUNTIME_PATH ENG_SHADER_VK_WORLD_FRAGMENT_OUTPUT
#define ENG_SHADER_WORLD_RESET_RUNTIME_PATH ENG_SHADER_VK_WORLD_RESET_OUTPUT
#define ENG_SHADER_WORLD_CULL_RUNTIME_PATH ENG_SHADER_VK_WORLD_CULL_OUTPUT
#define ENG_SHADER_WORLD_PREFIX_RUNTIME_PATH ENG_SHADER_VK_WORLD_PREFIX_OUTPUT
#define ENG_SHADER_WORLD_SCATTER_RUNTIME_PATH ENG_SHADER_VK_WORLD_SCATTER_OUTPUT
#define ENG_SHADER_WORLD_ARGS_RUNTIME_PATH ENG_SHADER_VK_WORLD_ARGS_OUTPUT
#elif defined(PLATFORM_OS_MACOS) || defined(SOB_MACOS)
#define ENG_SHADER_DRAW2D_VERTEX_RUNTIME_PATH ENG_SHADER_METAL_DRAW2D_VERTEX_OUTPUT
#define ENG_SHADER_DRAW2D_FRAGMENT_RUNTIME_PATH ENG_SHADER_METAL_DRAW2D_FRAGMENT_OUTPUT
#define ENG_SHADER_WORLD_VERTEX_RUNTIME_PATH ENG_SHADER_METAL_WORLD_VERTEX_OUTPUT
#define ENG_SHADER_WORLD_FRAGMENT_RUNTIME_PATH ENG_SHADER_METAL_WORLD_FRAGMENT_OUTPUT
#define ENG_SHADER_WORLD_RESET_RUNTIME_PATH ENG_SHADER_METAL_WORLD_RESET_OUTPUT
#define ENG_SHADER_WORLD_CULL_RUNTIME_PATH ENG_SHADER_METAL_WORLD_CULL_OUTPUT
#define ENG_SHADER_WORLD_PREFIX_RUNTIME_PATH ENG_SHADER_METAL_WORLD_PREFIX_OUTPUT
#define ENG_SHADER_WORLD_SCATTER_RUNTIME_PATH ENG_SHADER_METAL_WORLD_SCATTER_OUTPUT
#define ENG_SHADER_WORLD_ARGS_RUNTIME_PATH ENG_SHADER_METAL_WORLD_ARGS_OUTPUT
#else
#error No shader runtime backend configured for this platform.
#endif
