#pragma once

#define APP_SHADER_MANIFEST_SOURCE "app/shaders/shader_manifest.h"
#define APP_SHADER_OUTPUT_DIR "build/app/shaders"

#define APP_SHADER_SLANG_DRAW2D_SOURCE "app/shaders/draw2d.slang"
#define APP_SHADER_SLANG_ABI_SOURCE "app/shaders/gfx_shader_abi.slang"

#define APP_SHADER_DRAW2D_VERTEX_ENTRY "draw2d_vertex"
#define APP_SHADER_DRAW2D_FRAGMENT_ENTRY "draw2d_fragment"

#define APP_SHADER_VK_DRAW2D_VERTEX_OUTPUT APP_SHADER_OUTPUT_DIR "/draw2d_vertex.spv"
#define APP_SHADER_VK_DRAW2D_FRAGMENT_OUTPUT APP_SHADER_OUTPUT_DIR "/draw2d_fragment.spv"

#define APP_SHADER_METAL_DRAW2D_VERTEX_OUTPUT APP_SHADER_OUTPUT_DIR "/draw2d_vertex.metal"
#define APP_SHADER_METAL_DRAW2D_FRAGMENT_OUTPUT APP_SHADER_OUTPUT_DIR "/draw2d_fragment.metal"

#define APP_SHADER_SOURCE_LIST(X) \
    X(Draw2dSlang, APP_SHADER_SLANG_DRAW2D_SOURCE) \
    X(GfxShaderAbiSlang, APP_SHADER_SLANG_ABI_SOURCE)

#define APP_SHADER_VULKAN_OUTPUT_LIST(X) \
    X(Draw2dVertex, APP_SHADER_SLANG_DRAW2D_SOURCE, APP_SHADER_VK_DRAW2D_VERTEX_OUTPUT, APP_SHADER_DRAW2D_VERTEX_ENTRY, vertex, graphics) \
    X(Draw2dFragment, APP_SHADER_SLANG_DRAW2D_SOURCE, APP_SHADER_VK_DRAW2D_FRAGMENT_OUTPUT, APP_SHADER_DRAW2D_FRAGMENT_ENTRY, fragment, graphics)

#define APP_SHADER_METAL_OUTPUT_LIST(X) \
    X(Draw2dVertex, APP_SHADER_SLANG_DRAW2D_SOURCE, APP_SHADER_METAL_DRAW2D_VERTEX_OUTPUT, APP_SHADER_DRAW2D_VERTEX_ENTRY, vertex, graphics) \
    X(Draw2dFragment, APP_SHADER_SLANG_DRAW2D_SOURCE, APP_SHADER_METAL_DRAW2D_FRAGMENT_OUTPUT, APP_SHADER_DRAW2D_FRAGMENT_ENTRY, fragment, graphics)

#if defined(PLATFORM_OS_WINDOWS) || defined(SOB_WINDOWS)
#define APP_SHADER_DRAW2D_VERTEX_RUNTIME_PATH APP_SHADER_VK_DRAW2D_VERTEX_OUTPUT
#define APP_SHADER_DRAW2D_FRAGMENT_RUNTIME_PATH APP_SHADER_VK_DRAW2D_FRAGMENT_OUTPUT
#elif defined(PLATFORM_OS_MACOS) || defined(SOB_MACOS)
#define APP_SHADER_DRAW2D_VERTEX_RUNTIME_PATH APP_SHADER_METAL_DRAW2D_VERTEX_OUTPUT
#define APP_SHADER_DRAW2D_FRAGMENT_RUNTIME_PATH APP_SHADER_METAL_DRAW2D_FRAGMENT_OUTPUT
#else
#error No shader runtime backend configured for this platform.
#endif
