#pragma once

#define APP_SHADER_MANIFEST_SOURCE "app/shaders/shader_manifest.h"
#define APP_SHADER_OUTPUT_DIR "build/app/shaders"

#define APP_SHADER_SLANG_DEMO_SOURCE "app/shaders/demo.slang"
#define APP_SHADER_SLANG_ABI_SOURCE "app/shaders/gfx_shader_abi.slang"

#define APP_SHADER_TRIANGLE_VERTEX_ENTRY "triangle_vertex"
#define APP_SHADER_TRIANGLE_FRAGMENT_ENTRY "triangle_fragment"
#define APP_SHADER_DEMO_COMPUTE_ENTRY "demo_material_compute"

#define APP_SHADER_VK_TRIANGLE_VERTEX_OUTPUT APP_SHADER_OUTPUT_DIR "/triangle_vertex.spv"
#define APP_SHADER_VK_TRIANGLE_FRAGMENT_OUTPUT APP_SHADER_OUTPUT_DIR "/triangle_fragment.spv"
#define APP_SHADER_VK_DEMO_COMPUTE_OUTPUT APP_SHADER_OUTPUT_DIR "/demo_material_compute.spv"

#define APP_SHADER_METAL_TRIANGLE_VERTEX_OUTPUT APP_SHADER_OUTPUT_DIR "/triangle_vertex.metal"
#define APP_SHADER_METAL_TRIANGLE_FRAGMENT_OUTPUT APP_SHADER_OUTPUT_DIR "/triangle_fragment.metal"
#define APP_SHADER_METAL_DEMO_COMPUTE_OUTPUT APP_SHADER_OUTPUT_DIR "/demo_material_compute.metal"

#define APP_SHADER_SOURCE_LIST(X) \
    X(DemoSlang, APP_SHADER_SLANG_DEMO_SOURCE) \
    X(GfxShaderAbiSlang, APP_SHADER_SLANG_ABI_SOURCE)

#define APP_SHADER_VULKAN_OUTPUT_LIST(X) \
    X(TriangleVertex, APP_SHADER_SLANG_DEMO_SOURCE, APP_SHADER_VK_TRIANGLE_VERTEX_OUTPUT, APP_SHADER_TRIANGLE_VERTEX_ENTRY, vertex, graphics) \
    X(TriangleFragment, APP_SHADER_SLANG_DEMO_SOURCE, APP_SHADER_VK_TRIANGLE_FRAGMENT_OUTPUT, APP_SHADER_TRIANGLE_FRAGMENT_ENTRY, fragment, graphics) \
    X(DemoCompute, APP_SHADER_SLANG_DEMO_SOURCE, APP_SHADER_VK_DEMO_COMPUTE_OUTPUT, APP_SHADER_DEMO_COMPUTE_ENTRY, compute, compute)

#define APP_SHADER_METAL_OUTPUT_LIST(X) \
    X(TriangleVertex, APP_SHADER_SLANG_DEMO_SOURCE, APP_SHADER_METAL_TRIANGLE_VERTEX_OUTPUT, APP_SHADER_TRIANGLE_VERTEX_ENTRY, vertex, graphics) \
    X(TriangleFragment, APP_SHADER_SLANG_DEMO_SOURCE, APP_SHADER_METAL_TRIANGLE_FRAGMENT_OUTPUT, APP_SHADER_TRIANGLE_FRAGMENT_ENTRY, fragment, graphics) \
    X(DemoCompute, APP_SHADER_SLANG_DEMO_SOURCE, APP_SHADER_METAL_DEMO_COMPUTE_OUTPUT, APP_SHADER_DEMO_COMPUTE_ENTRY, compute, compute)

#if defined(PLATFORM_OS_WINDOWS) || defined(SOB_WINDOWS)
#define APP_SHADER_TRIANGLE_VERTEX_RUNTIME_PATH APP_SHADER_VK_TRIANGLE_VERTEX_OUTPUT
#define APP_SHADER_TRIANGLE_FRAGMENT_RUNTIME_PATH APP_SHADER_VK_TRIANGLE_FRAGMENT_OUTPUT
#define APP_SHADER_DEMO_COMPUTE_RUNTIME_PATH APP_SHADER_VK_DEMO_COMPUTE_OUTPUT
#elif defined(PLATFORM_OS_MACOS) || defined(SOB_MACOS)
#define APP_SHADER_TRIANGLE_VERTEX_RUNTIME_PATH APP_SHADER_METAL_TRIANGLE_VERTEX_OUTPUT
#define APP_SHADER_TRIANGLE_FRAGMENT_RUNTIME_PATH APP_SHADER_METAL_TRIANGLE_FRAGMENT_OUTPUT
#define APP_SHADER_DEMO_COMPUTE_RUNTIME_PATH APP_SHADER_METAL_DEMO_COMPUTE_OUTPUT
#else
#error No shader runtime backend configured for this platform.
#endif
