#pragma once

#define APP_SHADER_VULKAN_OUTPUT_DIR "build/app/shaders"

#define APP_SHADER_VK_TRIANGLE_VERTEX_SOURCE "app/shaders/triangle_vk.vert"
#define APP_SHADER_VK_TRIANGLE_VERTEX_OUTPUT APP_SHADER_VULKAN_OUTPUT_DIR "/triangle_vk.vert.spv"
#define APP_SHADER_VK_TRIANGLE_FRAGMENT_SOURCE "app/shaders/triangle_vk.frag"
#define APP_SHADER_VK_TRIANGLE_FRAGMENT_OUTPUT APP_SHADER_VULKAN_OUTPUT_DIR "/triangle_vk.frag.spv"
#define APP_SHADER_VK_DEMO_COMPUTE_SOURCE "app/shaders/demo_compute_vk.comp"
#define APP_SHADER_VK_DEMO_COMPUTE_OUTPUT APP_SHADER_VULKAN_OUTPUT_DIR "/demo_compute_vk.comp.spv"

#define APP_SHADER_VULKAN_LIST(X) \
    X(TriangleVertex, APP_SHADER_VK_TRIANGLE_VERTEX_SOURCE, APP_SHADER_VK_TRIANGLE_VERTEX_OUTPUT) \
    X(TriangleFragment, APP_SHADER_VK_TRIANGLE_FRAGMENT_SOURCE, APP_SHADER_VK_TRIANGLE_FRAGMENT_OUTPUT) \
    X(DemoCompute, APP_SHADER_VK_DEMO_COMPUTE_SOURCE, APP_SHADER_VK_DEMO_COMPUTE_OUTPUT)

#define APP_SHADER_METAL_TRIANGLE_SOURCE "app/shaders/triangle.metal"
#define APP_SHADER_METAL_DEMO_COMPUTE_SOURCE "app/shaders/demo_compute.metal"

#if defined(PLATFORM_OS_WINDOWS) || defined(SOB_WINDOWS)
#define APP_SHADER_TRIANGLE_VERTEX_RUNTIME_PATH APP_SHADER_VK_TRIANGLE_VERTEX_OUTPUT
#define APP_SHADER_TRIANGLE_FRAGMENT_RUNTIME_PATH APP_SHADER_VK_TRIANGLE_FRAGMENT_OUTPUT
#define APP_SHADER_DEMO_COMPUTE_RUNTIME_PATH APP_SHADER_VK_DEMO_COMPUTE_OUTPUT
#else
#define APP_SHADER_TRIANGLE_VERTEX_RUNTIME_PATH APP_SHADER_METAL_TRIANGLE_SOURCE
#define APP_SHADER_TRIANGLE_FRAGMENT_RUNTIME_PATH APP_SHADER_METAL_TRIANGLE_SOURCE
#define APP_SHADER_DEMO_COMPUTE_RUNTIME_PATH APP_SHADER_METAL_DEMO_COMPUTE_SOURCE
#endif
